platform:ios,'9.0'
target '百思不得姐' do
pod 'AFNetworking', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.1.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'Masonry'
pod 'DACircularProgress'
pod 'pop'
pod 'SDWebImage/GIF'
pod 'SDWebImage'
use_frameworks!
end
